package vapari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vapari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 21:01:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi87 */
  @Test
  public void testRekisteroi87() {    // Henkilo: 87
    Henkilo mikko1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 89", 0, mikko1.getTunnusNro()); 
    mikko1.rekisteroi(); 
    Henkilo mikko2 = new Henkilo(); 
    mikko2.rekisteroi(); 
    int n1 = mikko1.getTunnusNro(); 
    int n2 = mikko2.getTunnusNro(); 
    assertEquals("From: Henkilo line: 95", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString301 */
  @Test
  public void testToString301() {    // Henkilo: 301
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse(" 2 | Mika Malli | 030383-1333 | 040-1231234 | mika.malli@malli.malli   | Keskusta | Kauppakatu 1 | 40100 | Auttaja "); 
    assertEquals("From: Henkilo line: 304", true, henkilo.toString().equals("2|Mika Malli|030383-1333|040-1231234|mika.malli@malli.malli|Keskusta|Kauppakatu 1|40100|Auttaja")); 
  } // Generated by ComTest END
}