package vapari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import vapari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 21:01:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LisatiedotTest {



  // Generated by ComTest BEGIN
  /** testLisaa58 */
  @Test
  public void testLisaa58() {    // Lisatiedot: 58
    Lisatiedot jyvaskyla = new Lisatiedot(); 
    Lisatieto siivous = new Lisatieto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Lisatiedot line: 63", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista76 */
  @Test
  public void testPoista76() {    // Lisatiedot: 76
    Lisatiedot jyvaskyla = new Lisatiedot(); 
    Lisatieto siivous = new Lisatieto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Lisatiedot line: 81", 1, jyvaskyla.getMaara()); 
    jyvaskyla.poista(siivous.getRekisterointiNro()); 
    assertEquals("From: Lisatiedot line: 83", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaHenkilo101 */
  @Test
  public void testPoistaHenkilo101() {    // Lisatiedot: 101
    Lisatiedot jyvaskyla = new Lisatiedot(); 
    Lisatieto siivous = new Lisatieto(1, "siivous"); 
    siivous.rekisteroi(); 
    Lisatieto ruoanlaitto = new Lisatieto(1, "ruoanlaitto"); 
    ruoanlaitto.rekisteroi(); 
    Lisatieto nuohous = new Lisatieto(1, "nuohous"); 
    nuohous.rekisteroi(); 
    assertEquals("From: Lisatiedot line: 109", 0, jyvaskyla.getMaara()); 
    jyvaskyla.lisaa(siivous); 
    jyvaskyla.lisaa(ruoanlaitto); 
    jyvaskyla.lisaa(nuohous); 
    jyvaskyla.lisaa(nuohous); 
    assertEquals("From: Lisatiedot line: 114", 4, jyvaskyla.getMaara()); 
    jyvaskyla.poistaHenkilo(1); 
    assertEquals("From: Lisatiedot line: 116", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara134 */
  @Test
  public void testGetMaara134() {    // Lisatiedot: 134
    Lisatiedot jyvaskyla = new Lisatiedot(); 
    Lisatieto siivous = new Lisatieto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Lisatiedot line: 139", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedostonNimi226 */
  @Test
  public void testGetTiedostonNimi226() {    // Lisatiedot: 226
    Lisatiedot lisatiedot = new Lisatiedot(); 
    assertEquals("From: Lisatiedot line: 228", "lisatiedot.dat", lisatiedot.getTiedostonNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta253 
   * @throws YleisException when error
   */
  @Test
  public void testLueTiedostosta253() throws YleisException {    // Lisatiedot: 253
    Lisatiedot lisatiedot = new Lisatiedot(); 
    Lisatieto t1 = new Lisatieto(), t2 = new Lisatieto(); 
    t1.rekisteroi(); 
    t2.rekisteroi(); 
    t1.esimerkkiTiedot(); 
    t2.esimerkkiTiedot(); 
    assertEquals("From: Lisatiedot line: 262", 1, t1.getTunnusNro()); 
    assertEquals("From: Lisatiedot line: 263", 1, t2.getTunnusNro()); 
    String tiedosto = "testivapari.dat"; 
    File ftied = new File(tiedosto); 
    ftied.delete(); 
    try {
    lisatiedot.lueTiedostosta(tiedosto); 
    fail("Lisatiedot: 267 Did not throw YleisException");
    } catch(YleisException _e_){ _e_.getMessage(); }
    lisatiedot.lisaa(t1); 
    lisatiedot.lisaa(t2); 
    lisatiedot.tallenna(); 
    assertEquals("From: Lisatiedot line: 271", t1, lisatiedot.haeLisatieto(0)); 
    assertEquals("From: Lisatiedot line: 272", t2, lisatiedot.haeLisatieto(1)); 
    lisatiedot = new Lisatiedot(); 
    lisatiedot.lueTiedostosta(tiedosto); 
    lisatiedot.haeLisatieto(0).equals(t1); 
    lisatiedot.haeLisatieto(1).equals(t2); 
    assertEquals("From: Lisatiedot line: 277", true, ftied.delete()); 
  } // Generated by ComTest END
}