package vapari.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import vapari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 21:02:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LisatietoTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi77 */
  @Test
  public void testRekisteroi77() {    // Lisatieto: 77
    Lisatieto siivous = new Lisatieto(); 
    int n1 = siivous.rekisteroi(); 
    Lisatieto lumityot = new Lisatieto(); 
    int n2 = lumityot.rekisteroi(); 
    assertEquals("From: Lisatieto line: 82", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEsimerkkiTiedot96 */
  @Test
  public void testEsimerkkiTiedot96() {    // Lisatieto: 96
    Lisatieto siivous = new Lisatieto(); 
    siivous.rekisteroi(); 
    siivous.esimerkkiTiedot(); 
    assertEquals("From: Lisatieto line: 100", "lisätieto", siivous.getLisatieto()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLisatieto114 */
  @Test
  public void testGetLisatieto114() {    // Lisatieto: 114
    Lisatieto siivous = new Lisatieto(); 
    siivous.rekisteroi(); 
    siivous.esimerkkiTiedot(); 
    assertEquals("From: Lisatieto line: 118", "lisätieto", siivous.getLisatieto()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTunnusNro131 */
  @Test
  public void testGetTunnusNro131() {    // Lisatieto: 131
    Lisatieto siivous = new Lisatieto(); 
    siivous.setTunnusNro(2); 
    assertEquals("From: Lisatieto line: 134", 2, siivous.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetRekisterointiNro147 */
  @Test
  public void testGetRekisterointiNro147() {    // Lisatieto: 147
    Lisatieto siivous = new Lisatieto(); 
    Lisatieto lumityot = new Lisatieto(); 
    siivous.rekisteroi(); 
    lumityot.rekisteroi(); 
    assertEquals("From: Lisatieto line: 152", lumityot.getRekisterointiNro()-1, siivous.getRekisterointiNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetLisatieto165 */
  @Test
  public void testSetLisatieto165() {    // Lisatieto: 165
    Lisatieto siivous = new Lisatieto(); 
    siivous.setLisatieto("iso kämppä siivottavaksi"); 
    assertEquals("From: Lisatieto line: 168", "iso kämppä siivottavaksi", siivous.getLisatieto()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetTunnusNro181 */
  @Test
  public void testSetTunnusNro181() {    // Lisatieto: 181
    Lisatieto siivous = new Lisatieto(); 
    siivous.setTunnusNro(2); 
    assertEquals("From: Lisatieto line: 184", 2, siivous.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetRekNro197 */
  @Test
  public void testSetRekNro197() {    // Lisatieto: 197
    Lisatieto siivous = new Lisatieto(); 
    siivous.setRekNro(2); 
    assertEquals("From: Lisatieto line: 200", 2, siivous.getRekisterointiNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString230 */
  @Test
  public void testToString230() {    // Lisatieto: 230
    Lisatieto tieto = new Lisatieto(); 
    tieto.parse(" 2 | Auto kaytossa | 4 "); 
    assertEquals("From: Lisatieto line: 233", true, tieto.toString().equals("2|Auto kaytossa|4")); 
  } // Generated by ComTest END
}