package vapari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import vapari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 21:02:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TapahtumatTest {



  // Generated by ComTest BEGIN
  /** testLisaa61 */
  @Test
  public void testLisaa61() {    // Tapahtumat: 61
    Tapahtumat jyvaskyla = new Tapahtumat(); 
    Tapahtuma siivous = new Tapahtuma(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Tapahtumat line: 66", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista79 */
  @Test
  public void testPoista79() {    // Tapahtumat: 79
    Tapahtumat jyvaskyla = new Tapahtumat(); 
    Tapahtuma siivous = new Tapahtuma(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Tapahtumat line: 84", 1, jyvaskyla.getMaara()); 
    jyvaskyla.poista(siivous.getRekisterointiNro()); 
    assertEquals("From: Tapahtumat line: 86", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaHenkilo104 */
  @Test
  public void testPoistaHenkilo104() {    // Tapahtumat: 104
    Tapahtumat jyvaskyla = new Tapahtumat(); 
    Tapahtuma siivous = new Tapahtuma(1, "siivous", "11.2.2011", 2); 
    siivous.rekisteroi(); 
    Tapahtuma ruoanlaitto = new Tapahtuma(1, "ruoanlaitto", "12.2.2011", 2); 
    ruoanlaitto.rekisteroi(); 
    Tapahtuma nuohous = new Tapahtuma(1, "nuohous", "13.2.2011", 2); 
    nuohous.rekisteroi(); 
    assertEquals("From: Tapahtumat line: 112", 0, jyvaskyla.getMaara()); 
    jyvaskyla.lisaa(siivous); 
    jyvaskyla.lisaa(ruoanlaitto); 
    jyvaskyla.lisaa(nuohous); 
    jyvaskyla.lisaa(nuohous); 
    assertEquals("From: Tapahtumat line: 117", 4, jyvaskyla.getMaara()); 
    jyvaskyla.poistaHenkilo(1); 
    assertEquals("From: Tapahtumat line: 119", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara137 */
  @Test
  public void testGetMaara137() {    // Tapahtumat: 137
    Tapahtumat jyvaskyla = new Tapahtumat(); 
    Tapahtuma siivous = new Tapahtuma(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Tapahtumat line: 142", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedostonNimi268 */
  @Test
  public void testGetTiedostonNimi268() {    // Tapahtumat: 268
    Tapahtumat tapahtumat = new Tapahtumat(); 
    assertEquals("From: Tapahtumat line: 270", "tapahtumat.dat", tapahtumat.getTiedostonNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta295 
   * @throws YleisException when error
   */
  @Test
  public void testLueTiedostosta295() throws YleisException {    // Tapahtumat: 295
    Tapahtumat tapahtumat = new Tapahtumat(); 
    Tapahtuma t1 = new Tapahtuma(), t2 = new Tapahtuma(); 
    t1.rekisteroi(); 
    t2.rekisteroi(); 
    t1.esimerkkiTiedot(); 
    t2.esimerkkiTiedot(); 
    assertEquals("From: Tapahtumat line: 304", 1, t1.getTunnusNro()); 
    assertEquals("From: Tapahtumat line: 305", 1, t2.getTunnusNro()); 
    String tiedosto = "testivapari.dat"; 
    File ftied = new File(tiedosto); 
    ftied.delete(); 
    try {
    tapahtumat.lueTiedostosta(tiedosto); 
    fail("Tapahtumat: 309 Did not throw YleisException");
    } catch(YleisException _e_){ _e_.getMessage(); }
    tapahtumat.lisaa(t1); 
    tapahtumat.lisaa(t2); 
    tapahtumat.tallenna(); 
    assertEquals("From: Tapahtumat line: 313", t1, tapahtumat.haeTapahtuma(0)); 
    assertEquals("From: Tapahtumat line: 314", t2, tapahtumat.haeTapahtuma(1)); 
    tapahtumat = new Tapahtumat(); 
    tapahtumat.lueTiedostosta(tiedosto); 
    tapahtumat.haeTapahtuma(0).equals(t1); 
    tapahtumat.haeTapahtuma(1).equals(t2); 
    assertEquals("From: Tapahtumat line: 319", true, ftied.delete()); 
  } // Generated by ComTest END
}