package vapari.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import vapari.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.23 21:02:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ToiminnotTest {



  // Generated by ComTest BEGIN
  /** testLisaa102 */
  @Test
  public void testLisaa102() {    // Toiminnot: 102
    Toiminnot jyvaskyla = new Toiminnot(); 
    Toiminto siivous = new Toiminto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Toiminnot line: 107", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoista120 */
  @Test
  public void testPoista120() {    // Toiminnot: 120
    Toiminnot jyvaskyla = new Toiminnot(); 
    Toiminto siivous = new Toiminto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Toiminnot line: 125", 1, jyvaskyla.getMaara()); 
    jyvaskyla.poista(siivous.getRekisterointiNro()); 
    assertEquals("From: Toiminnot line: 127", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPoistaHenkilo145 */
  @Test
  public void testPoistaHenkilo145() {    // Toiminnot: 145
    Toiminnot jyvaskyla = new Toiminnot(); 
    Toiminto siivous = new Toiminto(1, "siivous"); 
    siivous.rekisteroi(); 
    Toiminto ruoanlaitto = new Toiminto(1, "ruoanlaitto"); 
    ruoanlaitto.rekisteroi(); 
    Toiminto nuohous = new Toiminto(1, "nuohous"); 
    nuohous.rekisteroi(); 
    assertEquals("From: Toiminnot line: 153", 0, jyvaskyla.getMaara()); 
    jyvaskyla.lisaa(siivous); 
    jyvaskyla.lisaa(ruoanlaitto); 
    jyvaskyla.lisaa(nuohous); 
    jyvaskyla.lisaa(nuohous); 
    assertEquals("From: Toiminnot line: 158", 4, jyvaskyla.getMaara()); 
    jyvaskyla.poistaHenkilo(1); 
    assertEquals("From: Toiminnot line: 160", 0, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetMaara178 */
  @Test
  public void testGetMaara178() {    // Toiminnot: 178
    Toiminnot jyvaskyla = new Toiminnot(); 
    Toiminto siivous = new Toiminto(); 
    siivous.rekisteroi(); 
    jyvaskyla.lisaa(siivous); 
    assertEquals("From: Toiminnot line: 183", 1, jyvaskyla.getMaara()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetTiedostonNimi270 */
  @Test
  public void testGetTiedostonNimi270() {    // Toiminnot: 270
    Toiminnot toiminnot = new Toiminnot(); 
    assertEquals("From: Toiminnot line: 272", "toiminnot.dat", toiminnot.getTiedostonNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta297 
   * @throws YleisException when error
   */
  @Test
  public void testLueTiedostosta297() throws YleisException {    // Toiminnot: 297
    Toiminnot toiminnot = new Toiminnot(); 
    Toiminto t1 = new Toiminto(), t2 = new Toiminto(); 
    t1.rekisteroi(); 
    t2.rekisteroi(); 
    t1.esimerkkiTiedot(); 
    t2.esimerkkiTiedot(); 
    assertEquals("From: Toiminnot line: 306", 1, t1.getTunnusNro()); 
    assertEquals("From: Toiminnot line: 307", 1, t2.getTunnusNro()); 
    String tiedosto = "testivapari.dat"; 
    File ftied = new File(tiedosto); 
    ftied.delete(); 
    try {
    toiminnot.lueTiedostosta(tiedosto); 
    fail("Toiminnot: 311 Did not throw YleisException");
    } catch(YleisException _e_){ _e_.getMessage(); }
    toiminnot.lisaa(t1); 
    toiminnot.lisaa(t2); 
    toiminnot.tallenna(); 
    assertEquals("From: Toiminnot line: 315", t1, toiminnot.haeToiminto(0)); 
    assertEquals("From: Toiminnot line: 316", t2, toiminnot.haeToiminto(1)); 
    toiminnot = new Toiminnot(); 
    toiminnot.lueTiedostosta(tiedosto); 
    toiminnot.haeToiminto(0).equals(t1); 
    toiminnot.haeToiminto(1).equals(t2); 
    assertEquals("From: Toiminnot line: 321", true, ftied.delete()); 
  } // Generated by ComTest END
}